/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.myapp.kafka.domain;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Order extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 3396196063303631278L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Order\",\"namespace\":\"com.myapp.kafka.domain\",\"fields\":[{\"name\":\"orderId\",\"type\":\"string\"},{\"name\":\"customerId\",\"type\":\"string\"},{\"name\":\"orderType\",\"type\":{\"type\":\"enum\",\"name\":\"OrderType\",\"symbols\":[\"ONLINE\",\"IN_STORE\",\"WHOLESALE\"],\"default\":\"ONLINE\"}},{\"name\":\"orderTime\",\"type\":\"long\"},{\"name\":\"totalAmount\",\"type\":\"double\"},{\"name\":\"lineItems\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"OrderLineItem\",\"fields\":[{\"name\":\"productId\",\"type\":\"string\"},{\"name\":\"productName\",\"type\":\"string\"},{\"name\":\"quantity\",\"type\":\"int\"},{\"name\":\"unitPrice\",\"type\":\"double\"}]},\"default\":[]}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Order> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Order> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Order> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Order> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Order> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Order to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Order from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Order instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Order fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence orderId;
  private java.lang.CharSequence customerId;
  private com.myapp.kafka.domain.OrderType orderType;
  private long orderTime;
  private double totalAmount;
  private java.util.List<com.myapp.kafka.domain.OrderLineItem> lineItems;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Order() {}

  /**
   * All-args constructor.
   * @param orderId The new value for orderId
   * @param customerId The new value for customerId
   * @param orderType The new value for orderType
   * @param orderTime The new value for orderTime
   * @param totalAmount The new value for totalAmount
   * @param lineItems The new value for lineItems
   */
  public Order(java.lang.CharSequence orderId, java.lang.CharSequence customerId, com.myapp.kafka.domain.OrderType orderType, java.lang.Long orderTime, java.lang.Double totalAmount, java.util.List<com.myapp.kafka.domain.OrderLineItem> lineItems) {
    this.orderId = orderId;
    this.customerId = customerId;
    this.orderType = orderType;
    this.orderTime = orderTime;
    this.totalAmount = totalAmount;
    this.lineItems = lineItems;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return orderId;
    case 1: return customerId;
    case 2: return orderType;
    case 3: return orderTime;
    case 4: return totalAmount;
    case 5: return lineItems;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: orderId = (java.lang.CharSequence)value$; break;
    case 1: customerId = (java.lang.CharSequence)value$; break;
    case 2: orderType = (com.myapp.kafka.domain.OrderType)value$; break;
    case 3: orderTime = (java.lang.Long)value$; break;
    case 4: totalAmount = (java.lang.Double)value$; break;
    case 5: lineItems = (java.util.List<com.myapp.kafka.domain.OrderLineItem>)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'orderId' field.
   * @return The value of the 'orderId' field.
   */
  public java.lang.CharSequence getOrderId() {
    return orderId;
  }


  /**
   * Sets the value of the 'orderId' field.
   * @param value the value to set.
   */
  public void setOrderId(java.lang.CharSequence value) {
    this.orderId = value;
  }

  /**
   * Gets the value of the 'customerId' field.
   * @return The value of the 'customerId' field.
   */
  public java.lang.CharSequence getCustomerId() {
    return customerId;
  }


  /**
   * Sets the value of the 'customerId' field.
   * @param value the value to set.
   */
  public void setCustomerId(java.lang.CharSequence value) {
    this.customerId = value;
  }

  /**
   * Gets the value of the 'orderType' field.
   * @return The value of the 'orderType' field.
   */
  public com.myapp.kafka.domain.OrderType getOrderType() {
    return orderType;
  }


  /**
   * Sets the value of the 'orderType' field.
   * @param value the value to set.
   */
  public void setOrderType(com.myapp.kafka.domain.OrderType value) {
    this.orderType = value;
  }

  /**
   * Gets the value of the 'orderTime' field.
   * @return The value of the 'orderTime' field.
   */
  public long getOrderTime() {
    return orderTime;
  }


  /**
   * Sets the value of the 'orderTime' field.
   * @param value the value to set.
   */
  public void setOrderTime(long value) {
    this.orderTime = value;
  }

  /**
   * Gets the value of the 'totalAmount' field.
   * @return The value of the 'totalAmount' field.
   */
  public double getTotalAmount() {
    return totalAmount;
  }


  /**
   * Sets the value of the 'totalAmount' field.
   * @param value the value to set.
   */
  public void setTotalAmount(double value) {
    this.totalAmount = value;
  }

  /**
   * Gets the value of the 'lineItems' field.
   * @return The value of the 'lineItems' field.
   */
  public java.util.List<com.myapp.kafka.domain.OrderLineItem> getLineItems() {
    return lineItems;
  }


  /**
   * Sets the value of the 'lineItems' field.
   * @param value the value to set.
   */
  public void setLineItems(java.util.List<com.myapp.kafka.domain.OrderLineItem> value) {
    this.lineItems = value;
  }

  /**
   * Creates a new Order RecordBuilder.
   * @return A new Order RecordBuilder
   */
  public static com.myapp.kafka.domain.Order.Builder newBuilder() {
    return new com.myapp.kafka.domain.Order.Builder();
  }

  /**
   * Creates a new Order RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Order RecordBuilder
   */
  public static com.myapp.kafka.domain.Order.Builder newBuilder(com.myapp.kafka.domain.Order.Builder other) {
    if (other == null) {
      return new com.myapp.kafka.domain.Order.Builder();
    } else {
      return new com.myapp.kafka.domain.Order.Builder(other);
    }
  }

  /**
   * Creates a new Order RecordBuilder by copying an existing Order instance.
   * @param other The existing instance to copy.
   * @return A new Order RecordBuilder
   */
  public static com.myapp.kafka.domain.Order.Builder newBuilder(com.myapp.kafka.domain.Order other) {
    if (other == null) {
      return new com.myapp.kafka.domain.Order.Builder();
    } else {
      return new com.myapp.kafka.domain.Order.Builder(other);
    }
  }

  /**
   * RecordBuilder for Order instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Order>
    implements org.apache.avro.data.RecordBuilder<Order> {

    private java.lang.CharSequence orderId;
    private java.lang.CharSequence customerId;
    private com.myapp.kafka.domain.OrderType orderType;
    private long orderTime;
    private double totalAmount;
    private java.util.List<com.myapp.kafka.domain.OrderLineItem> lineItems;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.myapp.kafka.domain.Order.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.orderId)) {
        this.orderId = data().deepCopy(fields()[0].schema(), other.orderId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.customerId)) {
        this.customerId = data().deepCopy(fields()[1].schema(), other.customerId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.orderType)) {
        this.orderType = data().deepCopy(fields()[2].schema(), other.orderType);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.orderTime)) {
        this.orderTime = data().deepCopy(fields()[3].schema(), other.orderTime);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.totalAmount)) {
        this.totalAmount = data().deepCopy(fields()[4].schema(), other.totalAmount);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.lineItems)) {
        this.lineItems = data().deepCopy(fields()[5].schema(), other.lineItems);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
    }

    /**
     * Creates a Builder by copying an existing Order instance
     * @param other The existing instance to copy.
     */
    private Builder(com.myapp.kafka.domain.Order other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.orderId)) {
        this.orderId = data().deepCopy(fields()[0].schema(), other.orderId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.customerId)) {
        this.customerId = data().deepCopy(fields()[1].schema(), other.customerId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.orderType)) {
        this.orderType = data().deepCopy(fields()[2].schema(), other.orderType);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.orderTime)) {
        this.orderTime = data().deepCopy(fields()[3].schema(), other.orderTime);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.totalAmount)) {
        this.totalAmount = data().deepCopy(fields()[4].schema(), other.totalAmount);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.lineItems)) {
        this.lineItems = data().deepCopy(fields()[5].schema(), other.lineItems);
        fieldSetFlags()[5] = true;
      }
    }

    /**
      * Gets the value of the 'orderId' field.
      * @return The value.
      */
    public java.lang.CharSequence getOrderId() {
      return orderId;
    }


    /**
      * Sets the value of the 'orderId' field.
      * @param value The value of 'orderId'.
      * @return This builder.
      */
    public com.myapp.kafka.domain.Order.Builder setOrderId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.orderId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'orderId' field has been set.
      * @return True if the 'orderId' field has been set, false otherwise.
      */
    public boolean hasOrderId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'orderId' field.
      * @return This builder.
      */
    public com.myapp.kafka.domain.Order.Builder clearOrderId() {
      orderId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'customerId' field.
      * @return The value.
      */
    public java.lang.CharSequence getCustomerId() {
      return customerId;
    }


    /**
      * Sets the value of the 'customerId' field.
      * @param value The value of 'customerId'.
      * @return This builder.
      */
    public com.myapp.kafka.domain.Order.Builder setCustomerId(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.customerId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'customerId' field has been set.
      * @return True if the 'customerId' field has been set, false otherwise.
      */
    public boolean hasCustomerId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'customerId' field.
      * @return This builder.
      */
    public com.myapp.kafka.domain.Order.Builder clearCustomerId() {
      customerId = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'orderType' field.
      * @return The value.
      */
    public com.myapp.kafka.domain.OrderType getOrderType() {
      return orderType;
    }


    /**
      * Sets the value of the 'orderType' field.
      * @param value The value of 'orderType'.
      * @return This builder.
      */
    public com.myapp.kafka.domain.Order.Builder setOrderType(com.myapp.kafka.domain.OrderType value) {
      validate(fields()[2], value);
      this.orderType = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'orderType' field has been set.
      * @return True if the 'orderType' field has been set, false otherwise.
      */
    public boolean hasOrderType() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'orderType' field.
      * @return This builder.
      */
    public com.myapp.kafka.domain.Order.Builder clearOrderType() {
      orderType = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'orderTime' field.
      * @return The value.
      */
    public long getOrderTime() {
      return orderTime;
    }


    /**
      * Sets the value of the 'orderTime' field.
      * @param value The value of 'orderTime'.
      * @return This builder.
      */
    public com.myapp.kafka.domain.Order.Builder setOrderTime(long value) {
      validate(fields()[3], value);
      this.orderTime = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'orderTime' field has been set.
      * @return True if the 'orderTime' field has been set, false otherwise.
      */
    public boolean hasOrderTime() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'orderTime' field.
      * @return This builder.
      */
    public com.myapp.kafka.domain.Order.Builder clearOrderTime() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'totalAmount' field.
      * @return The value.
      */
    public double getTotalAmount() {
      return totalAmount;
    }


    /**
      * Sets the value of the 'totalAmount' field.
      * @param value The value of 'totalAmount'.
      * @return This builder.
      */
    public com.myapp.kafka.domain.Order.Builder setTotalAmount(double value) {
      validate(fields()[4], value);
      this.totalAmount = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'totalAmount' field has been set.
      * @return True if the 'totalAmount' field has been set, false otherwise.
      */
    public boolean hasTotalAmount() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'totalAmount' field.
      * @return This builder.
      */
    public com.myapp.kafka.domain.Order.Builder clearTotalAmount() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'lineItems' field.
      * @return The value.
      */
    public java.util.List<com.myapp.kafka.domain.OrderLineItem> getLineItems() {
      return lineItems;
    }


    /**
      * Sets the value of the 'lineItems' field.
      * @param value The value of 'lineItems'.
      * @return This builder.
      */
    public com.myapp.kafka.domain.Order.Builder setLineItems(java.util.List<com.myapp.kafka.domain.OrderLineItem> value) {
      validate(fields()[5], value);
      this.lineItems = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'lineItems' field has been set.
      * @return True if the 'lineItems' field has been set, false otherwise.
      */
    public boolean hasLineItems() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'lineItems' field.
      * @return This builder.
      */
    public com.myapp.kafka.domain.Order.Builder clearLineItems() {
      lineItems = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Order build() {
      try {
        Order record = new Order();
        record.orderId = fieldSetFlags()[0] ? this.orderId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.customerId = fieldSetFlags()[1] ? this.customerId : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.orderType = fieldSetFlags()[2] ? this.orderType : (com.myapp.kafka.domain.OrderType) defaultValue(fields()[2]);
        record.orderTime = fieldSetFlags()[3] ? this.orderTime : (java.lang.Long) defaultValue(fields()[3]);
        record.totalAmount = fieldSetFlags()[4] ? this.totalAmount : (java.lang.Double) defaultValue(fields()[4]);
        record.lineItems = fieldSetFlags()[5] ? this.lineItems : (java.util.List<com.myapp.kafka.domain.OrderLineItem>) defaultValue(fields()[5]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Order>
    WRITER$ = (org.apache.avro.io.DatumWriter<Order>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Order>
    READER$ = (org.apache.avro.io.DatumReader<Order>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.orderId);

    out.writeString(this.customerId);

    out.writeEnum(this.orderType.ordinal());

    out.writeLong(this.orderTime);

    out.writeDouble(this.totalAmount);

    long size0 = this.lineItems.size();
    out.writeArrayStart();
    out.setItemCount(size0);
    long actualSize0 = 0;
    for (com.myapp.kafka.domain.OrderLineItem e0: this.lineItems) {
      actualSize0++;
      out.startItem();
      e0.customEncode(out);
    }
    out.writeArrayEnd();
    if (actualSize0 != size0)
      throw new java.util.ConcurrentModificationException("Array-size written was " + size0 + ", but element count was " + actualSize0 + ".");

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.orderId = in.readString(this.orderId instanceof Utf8 ? (Utf8)this.orderId : null);

      this.customerId = in.readString(this.customerId instanceof Utf8 ? (Utf8)this.customerId : null);

      this.orderType = com.myapp.kafka.domain.OrderType.values()[in.readEnum()];

      this.orderTime = in.readLong();

      this.totalAmount = in.readDouble();

      long size0 = in.readArrayStart();
      java.util.List<com.myapp.kafka.domain.OrderLineItem> a0 = this.lineItems;
      if (a0 == null) {
        a0 = new SpecificData.Array<com.myapp.kafka.domain.OrderLineItem>((int)size0, SCHEMA$.getField("lineItems").schema());
        this.lineItems = a0;
      } else a0.clear();
      SpecificData.Array<com.myapp.kafka.domain.OrderLineItem> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<com.myapp.kafka.domain.OrderLineItem>)a0 : null);
      for ( ; 0 < size0; size0 = in.arrayNext()) {
        for ( ; size0 != 0; size0--) {
          com.myapp.kafka.domain.OrderLineItem e0 = (ga0 != null ? ga0.peek() : null);
          if (e0 == null) {
            e0 = new com.myapp.kafka.domain.OrderLineItem();
          }
          e0.customDecode(in);
          a0.add(e0);
        }
      }

    } else {
      for (int i = 0; i < 6; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.orderId = in.readString(this.orderId instanceof Utf8 ? (Utf8)this.orderId : null);
          break;

        case 1:
          this.customerId = in.readString(this.customerId instanceof Utf8 ? (Utf8)this.customerId : null);
          break;

        case 2:
          this.orderType = com.myapp.kafka.domain.OrderType.values()[in.readEnum()];
          break;

        case 3:
          this.orderTime = in.readLong();
          break;

        case 4:
          this.totalAmount = in.readDouble();
          break;

        case 5:
          long size0 = in.readArrayStart();
          java.util.List<com.myapp.kafka.domain.OrderLineItem> a0 = this.lineItems;
          if (a0 == null) {
            a0 = new SpecificData.Array<com.myapp.kafka.domain.OrderLineItem>((int)size0, SCHEMA$.getField("lineItems").schema());
            this.lineItems = a0;
          } else a0.clear();
          SpecificData.Array<com.myapp.kafka.domain.OrderLineItem> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<com.myapp.kafka.domain.OrderLineItem>)a0 : null);
          for ( ; 0 < size0; size0 = in.arrayNext()) {
            for ( ; size0 != 0; size0--) {
              com.myapp.kafka.domain.OrderLineItem e0 = (ga0 != null ? ga0.peek() : null);
              if (e0 == null) {
                e0 = new com.myapp.kafka.domain.OrderLineItem();
              }
              e0.customDecode(in);
              a0.add(e0);
            }
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










