spring:
  application:
    name: kafka-producer-demo
  kafka:
    bootstrap-servers:
      - localhost:19092
      - localhost:19093
      - localhost:19094
    template:
      default-topic: orders-topic
    producer:
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      client-id: spring-boot-producer
      acks: all
      retries: 3
      properties:
        #
        enable.idempotence: true
        retry.backof.ms: 1000
        linger.ms: 100
        buffer.memory: 67108864
        request.timeout.ms: 10
        delivery.timeout.ms: 100
        retries.backoff.ms: 5

      batch-size: 131072


app:
  kafka:
    topic:
      orders: orders-topic
      partitions: 3
      replicas: 3

server:
  port: 8888