spring:
  application:
    name: kafka-producer-demo
  kafka:
    bootstrap-servers:
      - localhost:19092
      - localhost:19093
      - localhost:19094
    template:
      default-topic: ${app.kafka.topic.orders}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.apicurio.registry.serde.avro.AvroKafkaSerializer
      client-id: spring-boot-producer
      acks: all
      retries: 10
      properties:
        apicurio.registry.url: ${SCHEMA_REGISTRY_URL:http://localhost:8081/apis/registry/v3}
        apicurio.registry.auto-register: true
        # prevent duplicates
        enable.idempotence: true
        retry.backof.ms: 1000
        max.in.flight.requests.per.connection: 1
        compression.type: lz4
        linger.ms: 0
        buffer.memory: 67108864
        request.timeout.ms: 5000
        delivery.timeout.ms: 30000
        retry.backoff.ms: 5

      batch-size: 131072


app:
  kafka:
    topic:
      orders: orders-avro-topic
      partitions: 3
      replicas: 3

server:
  port: 8888

logging:
  level:
    org.apache.kafka.clients.producer: debug
    org.springframework.kafka: info